# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - v*

jobs:
  BuildBinaries:
    name: Build application packages
    strategy:
      matrix:
        runtime: [ linux-x64, osx-x64, win-x64 ]
        include:
        - runtime: linux-x64
          arch: x64
          os: ubuntu-latest
          shell: bash
          buildPackage: ./scripts/BuildLinuxDeb.sh
          buildJar: ./scripts/BuildUnixJar.sh
          
        - runtime: linux-centos-x64
          arch: x64
          os: ubuntu-latest
          shell: bash
          buildPackage: ./scripts/BuildLinuxRpm.sh
          buildJar: ./scripts/BuildUnixJar.sh

        - runtime: osx-x64
          arch: x64
          os: macOS-latest
          shell: bash
          buildPackage: ./scripts/BuildMacPkg.sh
          buildJar: ./scripts/BuildUnixJar.sh

        - runtime: win-x64
          arch: x64
          os: windows-latest
          shell: powershell
          buildPackage: ./scripts/BuildWindowsMsi.ps1
          buildJar: ./scripts/BuildWindowsJar.ps1

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      if: ${{ matrix.runtime != 'linux-centos-x64' }}
      with:
        java-version: '15'
        architecture: ${{ matrix.arch }}

    - name: Build Package
      if: ${{ matrix.runtime != 'linux-centos-x64' }}
      run: ${{ matrix.buildPackage }}

    - name: Build Jar
      if: ${{ matrix.runtime != 'linux-centos-x64' }}
      run: ${{ matrix.buildJar }}

    - name: Build rpm Package
      if: ${{ matrix.runtime == 'linux-centos-x64' }}
      uses: Syer10/CentOS-Java15-Action@v1
      with:
        command: ${{ matrix.buildPackage }}

    # Upload runner package tar.gz/zip as artifact
    - name: Publish Artifact
      uses: actions/upload-artifact@v1
      with:
        name: runner-package-${{ matrix.runtime }}
        path: |
          build/compose/binaries/main/*/*
          build/compose/jars/*.jar
  ReleaseBinaries:
    name: Make a release
    needs: [BuildBinaries]
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*/*.*,*.jar"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
