# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: Build application packages
    strategy:
      matrix:
        runtime: [ linux-x64, osx-x64, win-x64 ]
        include:
        - runtime: linux-x64
          arch: x64
          os: ubuntu-latest
          shell: bash
          buildPackage: ./scripts/BuildLinuxDeb.sh
          buildJar: ./scripts/BuildUnixJar.sh

        - runtime: osx-x64
          arch: x64
          os: macOS-latest
          shell: bash
          buildPackage: ./scripts/BuildMacPkg.sh
          buildJar: ./scripts/BuildUnixJar.sh

        - runtime: win-x64
          arch: x64
          os: windows-latest
          shell: powershell
          buildPackage: ./scripts/BuildWindowsMsi.ps1
          buildJar: ./scripts/BuildWindowsJar.ps1

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '15'
        architecture: ${{ matrix.arch }}

    - name: Build Package
      run: ${{ matrix.buildPackage }}

    - name: Build Jar
      run: ${{ matrix.buildJar }}

    # Upload runner package tar.gz/zip as artifact
    - name: Publish Artifact
      uses: actions/upload-artifact@v1
      with:
        name: runner-package-${{ matrix.runtime }}
        path: build/compose
