# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: Build application packages
    strategy:
      matrix:
        runtime: [ linux-x64, linux-x86, osx-x64, win-x64, win-x86 ]
        include:
        - runtime: linux-x64
          arch: x64
          os: ubuntu-latest
          buildPackage: ./scripts/BuildLinuxDeb.sh
          buildJar: ./scripts/BuildUnixJar.sh
          scriptShell: bash

        - runtime: linux-x86
          arch: x86
          os: ubuntu-latest
          buildPackage: ./scripts/BuildLinuxDeb.sh
          buildJar: ./scripts/BuildUnixJar.sh
          scriptShell: bash

        - runtime: osx-x64
          arch: x64
          os: macOS-latest
          buildPackage: ./scripts/BuildMacPkg.sh
          buildJar: ./scripts/BuildUnixJar.sh
          scriptShell: bash

        - runtime: win-x64
          arch: x64
          os: windows-latest
          buildPackage: ./scripts/BuildWindowsMsi.ps1
          buildJar: ./scripts/BuildWindowsJar.ps1
          scriptShell: powershell

        - runtime: win-x86
          arch: x86
          os: windows-latest
          buildPackage: ./scripts/BuildWindowsMsi.ps1
          buildJar: ./scripts/BuildWindowsJar.ps1
          scriptShell: powershell

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '15'
        architecture: ${{ matrix.arch }}

    - name: Build Package
      run: ${{ matrix.buildPackage }}
      shell: ${{ matrix.scriptShell }}

    - name: Build Jar
      run: ${{ matrix.buildJar }}
      shell: ${{ matrix.scriptShell }}

    # Upload runner package tar.gz/zip as artifact
    - name: Publish Artifact
      uses: actions/upload-artifact@v1
      with:
        name: runner-package-${{ matrix.runtime }}
        path: build/compose
