name: Validate
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          architecture: x64

      - name: Setup Cl
        run: ./scripts/SetupClUnix.sh

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
